//! # libstealthtech-bridge
//!
//! Native language bindings (Swift/Kotlin) for StealthTech via uniffi.
//!
//! This crate provides a clean FFI boundary between the Rust core library and
//! platform-specific bindings generated by uniffi. All types are redeclared at
//! the bridge level to keep the FFI surface stable and decoupled from internal
//! protocol evolution.

use std::sync::Arc;
use std::time::Duration;

uniffi::setup_scaffolding!();

// ============================================================================
// Error types
// ============================================================================

/// Errors exposed across the FFI boundary.
#[derive(Debug, uniffi::Error, thiserror::Error)]
pub enum StealthTechError {
    #[error("BLE error: {message}")]
    Ble { message: String },
    #[error("Connection error: {message}")]
    Connection { message: String },
    #[error("Protocol error: {message}")]
    Protocol { message: String },
    #[error("Not connected")]
    NotConnected,
}

impl From<anyhow::Error> for StealthTechError {
    fn from(err: anyhow::Error) -> Self {
        let message = err.to_string();
        let lower = message.to_lowercase();
        if lower.contains("connect") || lower.contains("reconnect") || lower.contains("timed out")
        {
            StealthTechError::Connection { message }
        } else if lower.contains("protocol")
            || lower.contains("encode")
            || lower.contains("decode")
            || lower.contains("out of range")
            || lower.contains("unknown byte")
        {
            StealthTechError::Protocol { message }
        } else {
            StealthTechError::Ble { message }
        }
    }
}

fn join_err(e: tokio::task::JoinError) -> StealthTechError {
    StealthTechError::Ble {
        message: format!("Task join error: {}", e),
    }
}

// ============================================================================
// Bridge enums (redeclared for clean FFI boundary)
// ============================================================================

#[derive(Debug, Clone, Copy, uniffi::Enum)]
pub enum BleInput {
    HdmiArc,
    Bluetooth,
    Aux,
    Optical,
}

impl From<BleInput> for libstealthtech_protocol::Input {
    fn from(input: BleInput) -> Self {
        match input {
            BleInput::HdmiArc => libstealthtech_protocol::Input::HdmiArc,
            BleInput::Bluetooth => libstealthtech_protocol::Input::Bluetooth,
            BleInput::Aux => libstealthtech_protocol::Input::Aux,
            BleInput::Optical => libstealthtech_protocol::Input::Optical,
        }
    }
}

impl From<libstealthtech_protocol::Input> for BleInput {
    fn from(input: libstealthtech_protocol::Input) -> Self {
        match input {
            libstealthtech_protocol::Input::HdmiArc => BleInput::HdmiArc,
            libstealthtech_protocol::Input::Bluetooth => BleInput::Bluetooth,
            libstealthtech_protocol::Input::Aux => BleInput::Aux,
            libstealthtech_protocol::Input::Optical => BleInput::Optical,
        }
    }
}

#[derive(Debug, Clone, Copy, uniffi::Enum)]
pub enum BleSoundMode {
    Movies,
    Music,
    Tv,
    News,
    Manual,
}

impl From<BleSoundMode> for libstealthtech_protocol::SoundMode {
    fn from(mode: BleSoundMode) -> Self {
        match mode {
            BleSoundMode::Movies => libstealthtech_protocol::SoundMode::Movies,
            BleSoundMode::Music => libstealthtech_protocol::SoundMode::Music,
            BleSoundMode::Tv => libstealthtech_protocol::SoundMode::Tv,
            BleSoundMode::News => libstealthtech_protocol::SoundMode::News,
            BleSoundMode::Manual => libstealthtech_protocol::SoundMode::Manual,
        }
    }
}

impl From<libstealthtech_protocol::SoundMode> for BleSoundMode {
    fn from(mode: libstealthtech_protocol::SoundMode) -> Self {
        match mode {
            libstealthtech_protocol::SoundMode::Movies => BleSoundMode::Movies,
            libstealthtech_protocol::SoundMode::Music => BleSoundMode::Music,
            libstealthtech_protocol::SoundMode::Tv => BleSoundMode::Tv,
            libstealthtech_protocol::SoundMode::News => BleSoundMode::News,
            libstealthtech_protocol::SoundMode::Manual => BleSoundMode::Manual,
        }
    }
}

#[derive(Debug, Clone, Copy, uniffi::Enum)]
pub enum BleConfigShape {
    Straight,
    LShape,
    UShape,
    Pit,
}

impl From<BleConfigShape> for libstealthtech_protocol::ConfigShape {
    fn from(shape: BleConfigShape) -> Self {
        match shape {
            BleConfigShape::Straight => libstealthtech_protocol::ConfigShape::Straight,
            BleConfigShape::LShape => libstealthtech_protocol::ConfigShape::LShape,
            BleConfigShape::UShape => libstealthtech_protocol::ConfigShape::UShape,
            BleConfigShape::Pit => libstealthtech_protocol::ConfigShape::Pit,
        }
    }
}

impl From<libstealthtech_protocol::ConfigShape> for BleConfigShape {
    fn from(shape: libstealthtech_protocol::ConfigShape) -> Self {
        match shape {
            libstealthtech_protocol::ConfigShape::Straight => BleConfigShape::Straight,
            libstealthtech_protocol::ConfigShape::LShape => BleConfigShape::LShape,
            libstealthtech_protocol::ConfigShape::UShape => BleConfigShape::UShape,
            libstealthtech_protocol::ConfigShape::Pit => BleConfigShape::Pit,
        }
    }
}

// ============================================================================
// Bridge records
// ============================================================================

#[derive(Debug, Clone, uniffi::Record)]
pub struct BleDeviceState {
    pub volume: Option<u8>,
    pub input: Option<String>,
    pub sound_mode: Option<String>,
    pub mute: Option<bool>,
    pub bass: Option<u8>,
    pub treble: Option<u8>,
    pub center_volume: Option<u8>,
    pub balance: Option<u8>,
    pub rear_channel_volume: Option<u8>,
    pub quiet_couch: Option<bool>,
    pub power: Option<bool>,
    pub firmware_version: Option<String>,
}

impl From<&libstealthtech_protocol::DeviceState> for BleDeviceState {
    fn from(state: &libstealthtech_protocol::DeviceState) -> Self {
        Self {
            volume: state.volume,
            input: state.input.map(|i| i.to_string()),
            sound_mode: state.sound_mode.map(|m| m.to_string()),
            mute: state.mute,
            bass: state.bass,
            treble: state.treble,
            center_volume: state.center_volume,
            balance: state.balance,
            rear_channel_volume: state.rear_channel_volume,
            quiet_couch: state.quiet_couch,
            power: state.power,
            firmware_version: state.firmware_version.clone(),
        }
    }
}

#[derive(Debug, Clone, uniffi::Record)]
pub struct BleDiscoveredDevice {
    pub name: Option<String>,
    pub address: String,
    pub rssi: Option<i16>,
}

// ============================================================================
// StealthTechBleDevice
// ============================================================================

/// High-level FFI wrapper around the core `StealthTechDevice`.
///
/// All methods use `tokio::task::spawn` internally because the underlying
/// btleplug + tracing futures hold non-Send temporaries across .await points.
/// uniffi requires all exported async methods to return Send futures.
#[derive(uniffi::Object)]
pub struct StealthTechBleDevice {
    inner: Arc<tokio::sync::Mutex<libstealthtech_core::device::StealthTechDevice>>,
}

#[uniffi::export(async_runtime = "tokio")]
impl StealthTechBleDevice {
    #[uniffi::constructor]
    pub async fn connect(address: String) -> Result<Arc<Self>, StealthTechError> {
        let device = tokio::task::spawn(async move {
            let scanner = libstealthtech_core::ble::scanner::Scanner::new().await?;
            let devices = scanner.scan(Duration::from_secs(10)).await?;
            let discovered = devices
                .into_iter()
                .find(|d| d.address == address)
                .ok_or_else(|| {
                    anyhow::anyhow!("Device with address '{}' not found during scan", address)
                })?;
            libstealthtech_core::device::StealthTechDevice::connect(discovered).await
        })
        .await
        .map_err(join_err)?
        .map_err(StealthTechError::from)?;

        Ok(Arc::new(Self {
            inner: Arc::new(tokio::sync::Mutex::new(device)),
        }))
    }

    pub async fn set_volume(&self, volume: u8) -> Result<(), StealthTechError> {
        let inner = self.inner.clone();
        tokio::task::spawn(async move { inner.lock().await.set_volume(volume).await })
            .await
            .map_err(join_err)?
            .map_err(StealthTechError::from)
    }

    pub async fn set_bass(&self, level: u8) -> Result<(), StealthTechError> {
        let inner = self.inner.clone();
        tokio::task::spawn(async move { inner.lock().await.set_bass(level).await })
            .await
            .map_err(join_err)?
            .map_err(StealthTechError::from)
    }

    pub async fn set_treble(&self, level: u8) -> Result<(), StealthTechError> {
        let inner = self.inner.clone();
        tokio::task::spawn(async move { inner.lock().await.set_treble(level).await })
            .await
            .map_err(join_err)?
            .map_err(StealthTechError::from)
    }

    pub async fn set_mute(&self, muted: bool) -> Result<(), StealthTechError> {
        let inner = self.inner.clone();
        tokio::task::spawn(async move { inner.lock().await.set_mute(muted).await })
            .await
            .map_err(join_err)?
            .map_err(StealthTechError::from)
    }

    pub async fn set_input(&self, input: BleInput) -> Result<(), StealthTechError> {
        let inner = self.inner.clone();
        tokio::task::spawn(async move { inner.lock().await.set_input(input.into()).await })
            .await
            .map_err(join_err)?
            .map_err(StealthTechError::from)
    }

    pub async fn set_sound_mode(&self, mode: BleSoundMode) -> Result<(), StealthTechError> {
        let inner = self.inner.clone();
        tokio::task::spawn(async move { inner.lock().await.set_sound_mode(mode.into()).await })
            .await
            .map_err(join_err)?
            .map_err(StealthTechError::from)
    }

    pub async fn set_power(&self, on: bool) -> Result<(), StealthTechError> {
        let inner = self.inner.clone();
        tokio::task::spawn(async move { inner.lock().await.set_power(on).await })
            .await
            .map_err(join_err)?
            .map_err(StealthTechError::from)
    }

    pub async fn set_quiet_couch(&self, enabled: bool) -> Result<(), StealthTechError> {
        let inner = self.inner.clone();
        tokio::task::spawn(async move { inner.lock().await.set_quiet_couch(enabled).await })
            .await
            .map_err(join_err)?
            .map_err(StealthTechError::from)
    }

    pub async fn set_center_volume(&self, level: u8) -> Result<(), StealthTechError> {
        let inner = self.inner.clone();
        tokio::task::spawn(async move { inner.lock().await.set_center_volume(level).await })
            .await
            .map_err(join_err)?
            .map_err(StealthTechError::from)
    }

    pub async fn set_rear_channel_volume(&self, level: u8) -> Result<(), StealthTechError> {
        let inner = self.inner.clone();
        tokio::task::spawn(async move {
            inner.lock().await.set_rear_channel_volume(level).await
        })
        .await
        .map_err(join_err)?
        .map_err(StealthTechError::from)
    }

    pub async fn set_balance(&self, balance: u8) -> Result<(), StealthTechError> {
        let inner = self.inner.clone();
        tokio::task::spawn(async move { inner.lock().await.set_balance(balance).await })
            .await
            .map_err(join_err)?
            .map_err(StealthTechError::from)
    }

    pub async fn get_state(&self) -> Result<BleDeviceState, StealthTechError> {
        let device = self.inner.lock().await;
        Ok(BleDeviceState::from(device.state()))
    }

    pub async fn disconnect(&self) -> Result<(), StealthTechError> {
        let inner = self.inner.clone();
        tokio::task::spawn(async move { inner.lock().await.disconnect().await })
            .await
            .map_err(join_err)?
            .map_err(StealthTechError::from)
    }
}

// ============================================================================
// BleScanner
// ============================================================================

#[derive(uniffi::Object)]
pub struct BleScanner {
    inner: Arc<tokio::sync::Mutex<libstealthtech_core::ble::scanner::Scanner>>,
}

#[uniffi::export(async_runtime = "tokio")]
impl BleScanner {
    #[uniffi::constructor]
    pub async fn new() -> Result<Arc<Self>, StealthTechError> {
        let scanner = tokio::task::spawn(async move {
            libstealthtech_core::ble::scanner::Scanner::new().await
        })
        .await
        .map_err(join_err)?
        .map_err(StealthTechError::from)?;

        Ok(Arc::new(Self {
            inner: Arc::new(tokio::sync::Mutex::new(scanner)),
        }))
    }

    pub async fn scan(
        &self,
        timeout_secs: u64,
    ) -> Result<Vec<BleDiscoveredDevice>, StealthTechError> {
        let inner = self.inner.clone();
        let devices = tokio::task::spawn(async move {
            let scanner = inner.lock().await;
            scanner.scan(Duration::from_secs(timeout_secs)).await
        })
        .await
        .map_err(join_err)?
        .map_err(StealthTechError::from)?;

        Ok(devices
            .into_iter()
            .map(|d| BleDiscoveredDevice {
                name: d.name,
                address: d.address,
                rssi: d.rssi,
            })
            .collect())
    }
}
